### ISSUE TITLE
Module not found: Can't resolve './navigation/NavBar'

### ISSUE THREAD

**Issue by dbit-xia** [dunky11/react-saas-template#25]
Project is very good! 
An error was found on linux: 
`Module not found: Can't resolve './navigation/NavBar' in '/home/dbit/下载/react-saas-template/src/logged_out/components'`

B should be uppercase
src/logged_out/components/navigation/Navbar.js  --> NavBar.js

**Comment by dunky11** [comment]
Thanks :) Its fixed now, was a dumb mistake by me .
