### ISSUE TITLE
Error during service worker registration

### ISSUE THREAD

**Issue by danielmpetrov** [dunky11/react-saas-template#298]
Hi, well done on the template.

I noticed a service worker registration error being logged in the console. You can verify this on the live demo - https://reactsaastemplate.com. I did an independent deployment of the template, and the same error is logged.

Chrome 88

![service-worker-error](https://user-images.githubusercontent.com/15656341/105578088-0f5dcc80-5d7e-11eb-96e2-727e340f0417.PNG)

Firefox 84

![service-worker-error-ff](https://user-images.githubusercontent.com/15656341/105578195-b17db480-5d7e-11eb-9d28-5239f0adbe5e.PNG)

Regards

**Comment by dunky11** [comment]
Thanks :) Something went wrong when I modified the serviceworker. I reset it to create-react-apps default service worker in https://github.com/dunky11/react-saas-template/commit/934002d72f610253132d1d0ce9d13294a74da50a and it should be working again.

**Comment by danielmpetrov** [comment]
It's working properly now. Cheers. 👍
