### ISSUE TITLE
Upgrade from mui v4 to mui v5?

### ISSUE THREAD

**Issue by openSourcerer9000** [dunky11/react-saas-template#513]
Any thought to doing this?

I'm trying to follow their guide but haven't been able to crack it as I don't really understand all the parts of the template. [https://mui.com/guides/migration-v4/](https://mui.com/guides/migration-v4/)

It seems there's lots of bug fixes in v5, as well as being benchmarked as 50% faster

**Comment by openSourcerer9000** [comment]
This is the issue I'm not understanding how to solve while trying to migrate:
`export 'isWidthUp' (imported as 'isWidthUp') was not found in '@mui/material'`

I'm following the steps exactly:
```
npm install @mui/material @mui/styles
npm install @emotion/react @emotion/styled
npx @mui/codemod v5.0.0/preset-safe <abs path to the repo>
```

**Comment by dunky11** [comment]
Wanted to do the upgrade for a couple of month now, shouldnt be too hard. However, there are a lot of stuff in the API of Material UI that changed in v5.
I will try to make the update during the next week.

**Comment by dunky11** [comment]
Yeah iswidthup doesnt exist anymore in v5

**Comment by openSourcerer9000** [comment]
OK, amazing. The steps provided in the MUI documentation seem to take care of most all the errors except for isWidthUp.

**Comment by dunky11** [comment]
Sorry, spend too much time on Elden Ring, the repo uses MUI v5 now

**Comment by openSourcerer9000** [comment]
Haha thanks I'll give it a go
